### Create a new todo
POST http://localhost:8080/todos
Content-Type: application/json

{
    "task": "Open Milk"
}

### Get all todos
GET http://localhost:8080/todos

### Delete a todo by ID
DELETE http://localhost:8080/todos/1